// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace CSF.Validation.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("CSF.Validation.Resources.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AccessorFunctionMustNotBeNull {
            get {
                return ResourceManager.GetString("AccessorFunctionMustNotBeNull", resourceCulture);
            }
        }
        
        internal static string MinMustNotBeGreaterThanMax {
            get {
                return ResourceManager.GetString("MinMustNotBeGreaterThanMax", resourceCulture);
            }
        }
        
        internal static string LengthMustNotBeNegative {
            get {
                return ResourceManager.GetString("LengthMustNotBeNegative", resourceCulture);
            }
        }
        
        internal static string DependencyMustHaveAResult {
            get {
                return ResourceManager.GetString("DependencyMustHaveAResult", resourceCulture);
            }
        }
        
        internal static string RuleMayNotBeExecuted {
            get {
                return ResourceManager.GetString("RuleMayNotBeExecuted", resourceCulture);
            }
        }
        
        internal static string RuleMustHaveAResult {
            get {
                return ResourceManager.GetString("RuleMustHaveAResult", resourceCulture);
            }
        }
        
        internal static string ProvideDependenciesMayOnlyBeCalledOnce {
            get {
                return ResourceManager.GetString("ProvideDependenciesMayOnlyBeCalledOnce", resourceCulture);
            }
        }
        
        internal static string DependenciesCannotBeRetrievedUntilProvided {
            get {
                return ResourceManager.GetString("DependenciesCannotBeRetrievedUntilProvided", resourceCulture);
            }
        }
        
        internal static string SomeValidationRulesCouldNotBeRun {
            get {
                return ResourceManager.GetString("SomeValidationRulesCouldNotBeRun", resourceCulture);
            }
        }
    }
}
