version: '{branch}-{build}'
image:
    - Visual Studio 2019
    - Ubuntu

environment:
    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
          JAVA_HOME: C:\Program Files\Java\jdk13
        - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
          JAVA_HOME: /usr/lib/jvm/jdk13

init:
    - cmd: git config --global core.autocrlf true
    
install:
    - git submodule update --init --recursive
    - cmd: dotnet tool install --global dotnet-sonarscanner
    
before_build:
    - dotnet --version
    - dotnet restore --verbosity m
    - cmd: dotnet-sonarscanner begin /k:"CSF.Validation" /v:AppVeyor_build_%APPVEYOR_BUILD_NUMBER% /o:craigfowler-github /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login=%SONARCLOUD_SECRET_KEY% /d:sonar.cs.nunit.reportsPaths=%APPVEYOR_BUILD_FOLDER%\CSF.Validation.Tests\TestResults\TestResults.xml /d:sonar.cs.opencover.reportsPaths=%APPVEYOR_BUILD_FOLDER%\CSF.Validation.Tests\TestResults\coverage.opencover.xml

build_script:
    - dotnet build

test_script:
    - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=\"json,opencover\" /p:CoverletOutput=\"TestResults/\"  --test-adapter-path:. --logger:\"nunit\"

after_test:
    - cmd: dotnet-sonarscanner end /d:"sonar.login=%SONARCLOUD_SECRET_KEY%"
